---
# server/roles/rear-test/tasks/main.yml

# configure-nfs-server.yml fails because rear was installed (on ther server and isolinux was an unresolvable package)
# As on 'server' we do not require rear we will remove it again ;-/
- name: Remove ReaR package on server (due to isolinux blocker)
  apt:
    name: rear
    state: absent

- include: configure-nfs-server.yml
- include: configure-and-start-dhcpd-tftp.yml
- include: start-samba.yml
- include: setup-bareos-server.yml


# Add various helpful configuration files
- name: Install the message of the day
  copy: src=motd dest=/etc/motd

