---
# ansible/server/roles/rear-test/tasks/setup-bareos-server.yml

- name: add http://download.bareos.org/bareos/release/latest/xUbuntu_14.04/ repo
  apt_repository:
    repo: deb http://download.bareos.org/bareos/release/latest/xUbuntu_14.04/ ./
    state: present
    update_cache: yes

#- name: copy bareos.repo to /etc/yum.repos.d directory
#  copy: src=bareos.repo dest=/etc/yum.repos.d/bareos.repo mode=0644 owner=root


# we have to be careful when we re-provision that the dir /var/lib/pgsql/ is wiped out
# before running initdb once again

- name: Remove directory /var/lib/pgsql/data
  file:
    path: /var/lib/pgsql/data
    state: absent

- name: Install postgresql
  package: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
   - postgresql
   - postgresql-contrib

# Seems the following is not necessary on ubuntu? (at least the binary is not found)
#- name: Initialize the postgresql database
#  command: /bin/postgresql-setup initdb
#  register: out

#- debug: var=out.stdout_lines

- name: Enable/Start database server
  service: name=postgresql state=started enabled=yes

- name: Install bareos server packages
  package: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
   - libfastlz
   - libjansson4
   - liblzo2-2
   - bareos-common
   - bareos 
   - bareos-database-postgresql

- name: copy bareos configuration files to /etc/bareos
  copy: src={{ item }} dest=/etc/bareos/{{ item }} owner=bareos group=bareos mode=0644
  with_items:
    - bareos-dir.conf
    - bareos-fd.conf
    - bareos-sd.conf
    - bconsole.conf

- name: mkdir /etc/bareos/bareos-dir.d
  file: path=/etc/bareos/bareos-dir.d state=directory mode=0755

- name: copy the client.conf file to /etc/bareos/bareos-dir.d
  copy: src=client.conf dest=/etc/bareos/bareos-dir.d/client.conf owner=bareos group=bareos mode=0644

- name: Run 'create_bareos_database' script
  shell: sleep 3; su postgres -c /usr/lib/bareos/scripts/create_bareos_database
  register: out
  async: 1
  poll: 0

#- debug: var=out.stdout_lines

- name:  Run 'make_bareos_tables' script
  shell: sleep 2; su postgres -c /usr/lib/bareos/scripts/make_bareos_tables
  register: out
  async: 1
  poll: 0

#- debug: var=out.stdout_lines

- name: Run 'grant_bareos_privileges' script
  shell: sleep 2; su postgres -c /usr/lib/bareos/scripts/grant_bareos_privileges
  register: out
  async: 1
  poll: 0

#- debug: var=out.stdout_lines

- name: Enable/Start bareos related services
  service: name={{ item }} state=started enabled=yes
  with_items:
   - bareos-dir
   - bareos-sd
   - bareos-fd
