---

- name: restart network service
  service: name=network state=restarted
  #when: ansible_os_family == "RedHat"

- name: restart networking service
  service: name=networking state=restarted
  #when: ansible_os_family == "Debian"
