---
# File ansible/common/roles/rear-test/tasks/update_all_packages.yml
#
# A work-around is https://github.com/ansible/ansible/issues/11620 for allow_unauthenticated:
#
- name: super-ugly hack to allow unauthenticated packages to install
  copy: content='APT::Get::AllowUnauthenticated "true";' dest=/etc/apt/apt.conf.d/99allowunauthenticated owner=root group=root mode=0644


# Below command returns an error when a prompt for Y/N was encountered with "upgrade=yes"
# Therefore, use upgrade=dist and add switch allow_unauthenticated=yes
- name: update all packages
  apt:
    upgrade: dist
    force: yes
    dpkg_options: 'force-confold,force-confdef'
