---
# server/roles/rear-test/tasks/main.yml

- include: configure-nfs-server.yml
- include: configure-and-start-dhcpd-tftp.yml
- include: start-samba.yml
- include: setup-bareos-server.yml

- name: Install packages required by the server only
  package: name={{ item }} state=present
  with_items:
    - nfs-utils
    - rpcbind

# Add various helpful configuration files
- name: Install the message of the day
  copy: src=motd dest=/etc/motd

