---
# server/roles/rear-test/tasks/main.yml

# As on 'server' we do not require rear we will remove it again - Ubuntu14 specific
# It block the proper installation of bareos due the isolinux package requirement.
# In the meantime, we moved rear install on debian/ubuntu to the client part only
# and it is the very last task to be executed which overcomes lots of issues
#- name: Remove ReaR package on server (due to isolinux blocker)
#  apt:
#    name: rear
#    state: absent
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'

- include_tasks: configure-nfs-server.yml
- include_tasks: configure-and-start-dhcpd-tftp.yml
- include_tasks: start-samba.yml
- include_tasks: setup-bareos-server.yml
- include_tasks: setup-duply-server.yml
  

# Add various helpful configuration files
- name: Install the message of the day
  copy: src=motd dest=/etc/motd

