---
# server/roles/rear-test/tasks/start-samba.yml

- name: start Samba (rh arch)
  service: name={{ item }} state=started enabled=yes
  with_items:
     - smb
     - nmb
  when: ansible_os_family == "RedHat"

- name: start Samba (deb arch)
  service: name={{ item }} state=started enabled=yes
  with_items:
     - smbd
     - nmbd
  when: ansible_os_family == "Debian"

# SELinux should be in permissive mode on all distro's
- name: run setsebool -P samba_enable_home_dirs on
  shell: sleep 1; setsebool -P samba_enable_home_dirs on
  async: 1
  poll: 0

- name: run restorecon -R /home/vagrant
  shell: sleep 1; restorecon -R /home/vagrant
  async: 1
  poll: 0

- name: adding user vagrant into smb passwd file with passwd vagrant
  shell: sleep 1; printf "vagrant\nvagrant\n" | smbpasswd -s -a vagrant
  async: 1
  poll: 0

# Access share as "mount -t cifs  //server/homes /mnt -o username=vagrant"
# Use "testparm -s" to view details of samba config on system "server"
