---
# centos7/ansible/client/roles/rear-test/tasks/gpgkey_generate.yml
# Originates from git@github.com:juju4/ansible-gpgkey_generate.git

- name: check entropy state
  command: "cat /proc/sys/kernel/random/entropy_avail"
  changed_when: false
  register: entropy

- name: entropy state
  debug: var=entropy

- name: Enable haveged - redhat
  service: name=haveged state=started enabled=yes
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: check entropy state
  command: "cat /proc/sys/kernel/random/entropy_avail"
  changed_when: false
  register: entropy2

- name: entropy state
  debug: var=entropy2

- debug: var=ansible_ssh_user
- debug: var=ansible_user
- debug: var=gpg_generator_user
- debug: var=gpg_user
- debug: var=gpg_home

- name: Ensure .gnupg config directory exists with right permissions
  file: dest={{ gpg_home }}/.gnupg state=directory mode=0700 owner="{{ gpg_generator_user }}"

# Only copy the gpg.conf for Gnupg version 1
- name: set defaut gpg options
  copy: src=gpg.conf-1 dest="{{ gpg_home }}/.gnupg/gpg.conf-1" mode=0600 owner="{{ gpg_generator_user }}"

- name: copy default template for gpg key generation
  template: src=gen-key-script dest="{{ gpg_home }}/.gnupg/gen-key-script-{{ gpg_user }}" mode=0600 owner="{{ gpg_generator_user }}"

## Note: matching on realname or email doesn't allow to create multiple keys. alternative?
- name: check existing secret key
  shell: "gpg --list-secret-keys | grep '{{ gpg_realname }}'"
  changed_when: false
  ignore_errors: true
  become: yes
  become_user: "{{ gpg_generator_user }}"
  register: gpgkeys
- debug: var=gpgkeys

- name: generate gpg key
  shell: |
     gpg --batch --gen-key {{ gpg_home }}/.gnupg/gen-key-script-{{ gpg_user }} chdir={{ gpg_home }}
  args:
    executable: /bin/bash
    creates: "{{ gpg_home }}/{{ gpg_pubkeyfile }}"
  become: yes
  become_user: "{{ gpg_generator_user }}"
  when: gpgkeys is defined and not gpgkeys.stdout
  register: genkey
#  no_log: "{{ gpg_no_log }}"
- debug: var=genkey

- name: GPG<2 | import generated keys
  command: "gpg --import {{ gpg_home }}/{{ gpg_pubkeyfile }} {{ gpg_home }}/{{ gpg_privkeyfile }}"
  become: yes
  become_user: "{{ gpg_generator_user }}"
  when: >
    gpgkeys is defined and not gpgkeys.stdout and
    not (
          (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 16) or
          (ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 7)
        )

- name: GPG>2 | import generated keys
  command: "gpg --import {{ gpg_home }}/{{ gpg_pubkeyfile }}"
  become: yes
  become_user: "{{ gpg_generator_user }}"
  when: >
    gpgkeys is defined and not gpgkeys.stdout and
    (
      (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 16) or
      (ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 7)
    )

- name: get user gpg fingerprint
  shell: |
     set -o pipefail
     gpg --list-keys --keyid-format LONG {{ gpg_useremail }} | awk -F'[ /]' '/sub/ { print $5 }' | tee {{ gpg_home }}/{{ gpg_fingerprint }}
  args:
    executable: /bin/bash
    creates: "{{ gpg_home }}/{{ gpg_fingerprint }}"
  register: gpg_user_fingerprint
  become: yes
  become_user: "{{ gpg_generator_user }}"

- name: get user armored public key
  shell: "gpg --export -a {{ gpg_useremail }} > {{ gpg_home }}/{{ gpg_pubkeyfileexport }}"
  changed_when: false
  become: yes
  become_user: "{{ gpg_generator_user }}"

- name: extract the GPG key (for duplicity/duply)
  shell: "gpg --list-keys --keyid-format LONG {{ gpg_generator_user }} | grep ^pub | awk '{print $2}' | tail -1 | cut -d/ -f2 | tee {{ gpg_home }}/{{ gpg_key }}"
  changed_when: false
  become: yes
  become_user: "{{ gpg_generator_user }}"

#### no clue anymore what the output was before???
#- name: trust the GPG key (for duplicity)
#  shell: "echo $(gpg --list-keys --fingerprint | grep `cat {{ gpg_home }}/{{ gpg_key }}` -A 1 | tail -1 | tr -d '[:space:]' | awk 'BEGIN { FS = \"=\" } ; { print $2 }'):6 | gpg --import-ownertrust"

#### we comment out the following 2 tasks as we do not need exported gpg key nor fingerprint on the hypervisor (yet)
#- debug: var=gpg_pull
#- name: fetch files to orchestrator
#  fetch: "src={{ item }} dest={{ gpg_pulldir }}/ flat=yes"
#  with_items:
##    - "{{ gpg_home }}/{{ gpg_privkeyfile }}"
##    - "{{ gpg_home }}/{{ gpg_pubkeyfile }}"
#    - "{{ gpg_home }}/{{ gpg_pubkeyfileexport }}"
#    - "{{ gpg_home }}/{{ gpg_fingerprint }}"
#  when: gpg_pull is defined and gpg_pull
#
#- name: fetch privatekey file to orchestrator
#  fetch: "src={{ item }} dest={{ gpg_pulldir }}/ flat=yes"
#  with_items:
#    - "{{ gpg_home }}/{{ gpg_privkeyfile }}"
#  when: gpg_pull is defined and gpg_pull and gpg_pull_privatekey is defined and gpg_pull_privatekey


