---
# playbook ansible/client/roles/rear-test/tasks/install_gnupg_software.yml
#

- name: install GNU Privacy Guard v2 software (RH family)
  package: name={{ item }} state=present
  with_items:
    - gnupg2
    - haveged
    - rng-tools
    - acl
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Create symbolic link from /bin/gpg2 towards /bin/gpg
  file:
    src: "/bin/gpg2"
    dest: "/bin/gpg"
    state: link
  when: ansible_os_family == "RedHat"

- name: install GNU Privacy Guard v2 software (Debian/Ubuntu family more recent versions)
  package: name={{ item }} state=present
  with_items:
    - gpgv2
    - rng-tools
    # https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
    - acl
  when: (ansible_distribution == 'Debian' and ansible_distribution_version|int >= 7) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 14)

- name: install GNU Privacy Guard software (Debian/Ubuntu family for older versions)
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - rng-tools
    - gnupg
  when: (ansible_distribution == 'Debian' and ansible_distribution_version|int < 7) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int < 14)
