---
# File: ansible/client/roles/rear-test/tasks/main.yml
# Ansible tasks meant for the client only

- include: github_pub_key.yml
- include: setup-bareos-client.yml

- name: Install redhat test tools, beakerlib packages and some other goodies (rh arch)
  package: name={{ item }} state=present
  with_items:
    - rear-rhts
    - beakerlib
  when: ansible_os_family == "RedHat"

- name: Install some tools useful on the client (all arch)
  package: name={{ item }} state=present
  with_items:
    - nano

# Add various helpful configuration files
- name: Install the message of the day
  copy: src=motd dest=/etc/motd

