---
# ansible/client/roles/rear-test/tasks/setup-bareos-client.yml

- name: Install bareos client packages (rh arch)
  package: name={{ item }} state=present
  with_items:
   - bareos-filedaemon
   - bareos-bconsole
  when: ansible_os_family == "RedHat"

####

- name: Install bareos pre-requisites for ubuntu14 only
  package: name={{ item }} state=present force=yes  allow_unauthenticated=yes
  with_items:  
   - libjansson4
   - libfastlz
   - liblzo2-2
  ignore_errors: True
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'


- name: install bareos-common package for ubuntu14 only
  package: name=bareos-common state=present force=yes  allow_unauthenticated=yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'

- name: Install bareos client packages (deb arch)
  package: name={{ item }} state=present  allow_unauthenticated=yes
  with_items:
   - bareos-filedaemon
   - bareos-bconsole
  when: ansible_os_family == "Debian"

####

- name: Install bareos client package (incl. pre-requisites) for SLES12
  package: name={{ item }} state=present
  with_items:
    - bareos-filedaemon
    - bareos-bconsole
  when: ansible_os_family == "Suse"

####

- name: copy bareos configuration files to /etc/bareos
  copy: src={{ item }} dest=/etc/bareos/{{ item }} owner=bareos group=bareos mode=0644
  with_items:
    - bareos-fd.conf
    - bconsole.conf

- name: Create /usr/local/bin directory (if required)
  file: path=/usr/local/bin state=directory

- name: copy the pre-backup script for rear/bareos (rear mkbackup calls this one)
  copy: src=client-backup-with-bareos dest=/usr/local/bin/client-backup-with-bareos owner=root mode=0755

- name: Enable/Start bareos related services
  service: name={{ item }} state=started enabled=yes
  with_items:
   - bareos-fd
