---
# File: ansible/client/roles/rear-test/tasks/setup_duply_client.yml

- name: Create the /root/.duply/duply-client directory
  file: path=/root/.duply/duply-client state=directory mode=0700

- name: Copy the duply configuration to /root/.duply/duply-client
  copy: src=duply.conf dest=/root/.duply/duply-client/conf mode=0600

- name: Copy the exclude file
  copy: src=exclude dest=/root/.duply/duply-client/exclude mode=0600

# now we have all software and configuration files in place; test it
# We might run into trouble as on server:/root/backup might not yet be created
# when we run this test
- name: Run duply status check
  shell: "echo yes | duply duply-client status"
  become: yes
  become_user: "{{ gpg_generator_user }}"
  register: command_result
  ignore_errors: True

#- debug: var=command_result
