---
# File: ansible/common/roles/rear-test/tasks/main.yml
# Ansible taks which are common for client and server

- include: define_timezone.yml
- include: apt_add_repositories.yml
- include: update_all_packages.yml
- include: create_users.yml
- include: create_private_ssh_key.yml
- include: configure_kernel_parameters.yml
- include: update_sshd_config.yml
#- include: update_and_restart_network.yml
- include: disable_biosdevnames.yml
#- include: change_selinux_state.yml


# Add various helpful configuration files
- name: Install the hosts file
  copy: src=hosts dest=/etc/hosts mode=0644

- name: Install common packages required by ReaR
  package: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
    - syslinux
    - syslinux-utils
    - cifs-utils
    - genisoimage
    - net-tools
    - samba
    - samba-common
    - bind9utils
    - rear
    - mtools
    - attr
    - sshfs
    - bc
    - nfs-common
    - git
    - tree
    - vim
    - wget
    # selinux gives unexpected errors that we do not understand (for the moment)
    #- selinux


- include: update_imapd_conf.yml

