---
# File: ansible/client/roles/rear-test/tasks/main.yml
# Ansible tasks meant for the client only

- include: github_pub_key.yml
- include: setup-bareos-client.yml

- name: Install other goodies
  package: name={{ item }} state=present
  with_items:
    - nano

# Add various helpful configuration files
- name: Install the message of the day
  copy: src=motd dest=/etc/motd

