---
# ansible/common/roles/rear-test/tasks/apt_add_repositories.yml

# Be careful - we are working with Snapshots here - for Stable release we still need to figure it out (TODO)
##########################################
# Specific section for Ubuntu distribution
##########################################
# manual action on VM works fine:
# # wget -q -O - download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/xUbuntu_16.04/Release.key | apt-key add -
# OK

- name: download the Release.key from OBS of rear "snapshot"
  apt_key:
    url: http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/xUbuntu_{{ ansible_distribution_version }}/Release.key
    state: present
  when: ansible_distribution == "Ubuntu"

- name: add http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/xUbuntu repo
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/xUbuntu_{{ ansible_distribution_version }}/ ./
    #repo: deb http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_17.04/ ./
    # Downloading stable version can better be done from https://launchpad.net/ubuntu/+source/rear
    # However, the real URL is not found yet
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: download the Release.key from OBS of rear "stable"
  apt_key:
    url: http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_{{ ansible_distribution_version }}/Release.key
    state: present
  when: ansible_distribution == "Ubuntu"

- name: add http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu repo
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/xUbuntu_{{ ansible_distribution_version }}/ ./
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

# alternative example:
# when: ansible_distribution == RedHat AND ansible_distribution_major_version == 6

###################################################################################################################
######################
# A section for Debian
######################
- name: download the Release.key from OBS of rear "Snapshot"
  apt_key:
    url: http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/Debian_{{ ansible_distribution_version }}/Release.key
    state: present
  when: ansible_distribution == "Debian"

- name: add http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/Debian repo
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/Debian_{{ ansible_distribution_version }}/ ./
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"

#### continue for other common tasks for Ubuntu/Debian:

