---
# ansible/common/roles/rear-test/tasks/change_selinux_state.yml

- name: change the selinux to permissive
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"

# With Ubuntu 14 we always get the error "sudo: a password is required" and then the playbook halts
# When we try it manually on the 'client' we get the following:
#  # setenforce disabled
#  setenforce: SELinux is disabled
#  # setenforce enabled
#  setenforce: SELinux is disabled
# For these reasons we think it is wiser to skip the ubuntu 14 selinux task altogether
#- name: change the selinux to disabled (for ubuntu 14)
#  selinux:
#    state: disabled
#  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'

- name: change the selinux to permissive (ubuntu =16)
  selinux:
    policy: targeted
    state: permissive
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16'

# selinux on ubuntu18 is by default permissive and https://github.com/gdha/rear-automated-testing/issues/73
# shows that there are issues with defining selinux policy
# Experimentation proofed that SELinux performance is really bad on the Ubuntu boxes, therefore, it is better
# to just disable SELinux on ubuntu alltogether.

- name: Disable SELinux on Ubuntu distribution
  lineinfile:
     dest=/etc/selinux/config
     regexp="{{ item.regexp }}"
     line="{{ item.line }}"
     state=present
  with_items:
    - regexp: "^SELINUX="
      line: "SELINUX=disabled"
  when: ansible_distribution == 'Ubuntu'

- name: temporarely turning off selinux
  shell: echo 0 > /sys/fs/selinux/enforce
  ignore_errors: True
