---
# File: ansible/common/roles/rear-test/tasks/copy_zyp_repos.yml for SLES

# the ReaR Snapshot YUM repo
# We use OpenSUSE Leap 42.3 as SLES12 SP3 distro (closest match in open source version)
- zypper_repository:
    name: Relax-and-Recover snapshot packages (SLE_12_SP3)
    repo: "http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/SLE_12_SP3/"
    #auto_import_keys: yes
    #disable_gpg_check: yes
    state: present
  when: ansible_os_family == "Suse" and ansible_distribution_major_version == "42"

# the ReaR Stable YUM repo
- zypper_repository:
    name: Relax-and-Recover (SLE_12_SP3)
    repo: "http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/SLE_12_SP3/"
    #auto_import_keys: yes
    #disable_gpg_check: yes
    state: present
  when: ansible_os_family == "Suse" and ansible_distribution_major_version == "42"

# the ReaR Stable and Snapshot Zypper repos
- name: add zypper repo for ReaR Stable (SLE11)
  template: src=rear-stable.repo.sles11.j2 dest=/etc/zypp/repos.d/rear-stable.repo mode=0644 owner=root
  when: ansible_os_family == "Suse" and ansible_distribution_major_version == "11"

- name: add zypper repo for ReaR Snapshot (SLE11)
  template: src=rear-snapshot.repo.sles11.j2 dest=/etc/zypp/repos.d/rear-snapshot.repo mode=0644 owner=root
  when: ansible_os_family == "Suse" and ansible_distribution_major_version == "11"

#- zypper_repository:
#    repo: "http://download.opensuse.org/repositories/home:/gdha/SLE_12/home:gdha.repo"
#    auto_import_keys: yes
#    disable_gpg_check: yes
#    state: present
#  when: ansible_os_family == "Suse" 

- name: Refresh the repos while importing the gpg keys with zypper
  command: zypper --gpg-auto-import-keys ref
