---
# ansible/common/roles/rear-test/tasks/create_bareos_apt_source.yml
# Define the APT repository definitions for Ubuntu only for the moment

- name: Download the Release.key from bareos
  apt_key:
    url: "{{ bareos_url }}/xUbuntu_{{ ansible_distribution_version }}/Release.key"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: add http://download.bareos.org/bareos/release/latest/xUbuntu repo
  apt_repository:
    repo: "deb {{ bareos_url }}/xUbuntu_{{ ansible_distribution_version }}/ ./"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

