---
# ansible/common/roles/rear-test/tasks/define_timezone.yml

- name: define timezone to Europe/Brussels
  command: /usr/bin/timedatectl set-timezone Europe/Brussels

- name: disable RTC time in the local time zone
  command: /usr/bin/timedatectl set-local-rtc 0

- name: display timezone
  command: /usr/bin/timedatectl
  register: out

- debug: var=out.stdout_lines
