---
# ansible/common/roles/rear-test/tasks/disable_biosdevnames.yml

- name: remove the udev net rules
  file:
    path: "{{item}}"
    state: absent
  with_fileglob:
    - "/etc/udev/rules.d/*persistent-net.rules"
    - "/etc/udev/rules.d/*-net.rules"

- name: clear the content of /var/lib/dhclient
  file:
    path: "{{item}}"
    state: absent
    recurse: yes
  with_fileglob:
    - "/var/lib/dhclient/*"
