---
# Install debian/ubuntu related packages required by rear

- name: Install packages required by ReaR
  package: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
    - syslinux
    - syslinux-common
    - cifs-utils
    - genisoimage
    - net-tools
    - samba
    - samba-common
    - samba-client
    - bind9utils
    - nfs-common
    - ethtool
    - libisoburn1
    - libburn4
    - libisofs6
    - libjte1
    - xorriso
    - iproute
    - libsigsegv2
    - selinux
  ignore_errors: True

# download the rear package locally and install it at the very end on the client only
# via ansible/client/roles/rear-test/tasks/install_rear_deb_pkg_at_the_end.yml
# as ubuntu14 is real pain to provision due to the missing isolinux package
# and that comes from rear Depends rule (unfortunately)
- name: download rear package locally
  shell: apt-get download rear
  async: 1
  poll: 0

