---
# common/install_common_packages.yml
# Here we install packages which are named the same across all supported distro's

# we added ignore_errors: True because 'ntpdate' is not available on SLES
- name: Install common basic development packages
  package: name={{ item }} state=present
  with_items:
    - git
    - tree
    - wget
    - bc
    - gawk
    - bash
    - attr
    - postfix
  ignore_errors: True
