# common/install_prereq_pkgs_fedora.yml
# uses selinux but python bindings (libselinux-python) required

- name: Install pre-requisite packages for Fedora
  package: name={{ item }} state=present
  with_items:
    - pstree
    - python3-libselinux
    - python3-dnf
    - dlrn
    - python3-dlrn
    - dnf-utils
    - dnf-yum
    - make
    - gcc
    - perl
    - kernel-headers
    #- kernel-devel
  ignore_errors: True
