---
# File: ansible/common/roles/rear-test/tasks/main.yml
# Ansible taks which are common for client and server

# The following set are the same for RedHat and Debian OS family
- include: define_timezone.yml
- include: chrony_service_install_config.yml
- include: create_private_ssh_key.yml
- include: update_sshd_config.yml
- include: configure_kernel_parameters.yml
- include: update_imapd_conf.yml
- include: install_common_packages.yml

# A block dedicated for ansible_os_family == "RedHat"
- block:
  - include: update_rh_packages.yml
  - include: copy_repos.yml
  - include: install_rh_packages.yml
  - include: install_rear_rh_packages.sh

  when: ansible_os_family == "RedHat"

# A block dedicated for ansible_os_family == "Debian"
- block:
  - include: update_deb_packages.yml
  - include: apt_add_repositories.yml
  - include: install_deb_packages.yml
  - include: install_rear_deb_packages.yml

  when: ansible_os_family == "Debian"

#############################################
# Common tasks for RedHat and Ubuntu
- include: create_users.yml
- include: update_and_restart_network.yml
- include: disable_biosdevnames.yml
- include: change_selinux_state.yml


# Add various helpful configuration files
- name: Install the hosts file
  copy: src=hosts dest=/etc/hosts mode=0644

