---
# File: ansible/common/roles/rear-test/tasks/main.yml
# Ansible taks which are common for client and server

- name: Check pre-requisites for Fedora distribution
  block:
    - include_tasks: install_prereq_pkgs_fedora.yml
  when: ansible_distribution == 'Fedora'

# Add various helpful configuration files
- name: Install the hosts file
  copy: src=hosts dest=/etc/hosts mode=0644

# The following set are the same for RedHat, SLES and Debian OS family
- include_tasks: bareos_ini_file.yml
- include_tasks: create_private_ssh_key.yml
- include_tasks: update_sshd_config.yml
- include_tasks: configure_kernel_parameters.yml
- include_tasks: update_imapd_conf.yml
- include_tasks: install_common_packages.yml

# A block dedicated for ansible_os_family == "RedHat"
- name: A block common for RedHat OS families
  block:
    - include_tasks: define_timezone.yml
    - include_tasks: chrony_service_install_config.yml
    - include_tasks: create_bareos_repo.yml
    - include_tasks: update_rh_packages.yml
    - include_tasks: copy_yum_repos.yml
    - include_tasks: install_rh_packages.yml
    - include_tasks: install_rear_rh_packages.yml
  when: ansible_os_family == 'RedHat'

# A block for RH/CentOS 8.x specific (e.g. issue #77)
- name : A block for RedHat OS major version 8
  block:
    - include_tasks: install_rhel8_packages.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

# A block dedicated for ansible_os_family == "Suse" (commont for SLES 11 and 12)
- name: A block common for SuSe SLES 11 and 12 families
  block:
    - include_tasks: zyppper_add_bareos_sles.yml
    - include_tasks: update_zyp_packages.yml
    - include_tasks: copy_zyp_repos.yml
    - include_tasks: install_sles_packages.yml
    - include_tasks: install_rear_sles_packages.yml
  when: ansible_os_family == 'Suse'

# A block dedicated for SLES 12 only
- name: A block dedicated for SLES 12
  block:
    # datetimectl does not exist on SLES11 - see issue #56
    - include_tasks: define_timezone.yml
    # chronyd does not exist on SLES 11 - use ntp instead
    - include_tasks: chrony_service_install_config.yml
  when: ansible_os_family == 'Suse' and ansible_distribution_major_version == '42'

# A block dedicated for ansible_os_family == "Debian"
- name: A block common for Debian alike families
  block:
    - include_tasks: define_timezone.yml
    - include_tasks: chrony_service_install_config.yml
    - include_tasks: create_bareos_apt_source.yml
    - include_tasks: update_deb_packages.yml
    - include_tasks: apt_add_rear_repositories.yml
    - include_tasks: install_deb_packages.yml
    - include_tasks: install_rear_deb_packages.yml
  when: ansible_os_family == 'Debian'

#############################################
# Common tasks for RedHat, SLES and Ubuntu
- include_tasks: create_users.yml
- include_tasks: update_and_restart_network.yml
- include_tasks: disable_biosdevnames.yml
- include_tasks: change_selinux_state.yml
- include_tasks: disable_postfix_service.yml
