---
# File: ansible/common/roles/rear-test/tasks/main.yml
# Ansible taks which are common for client and server

# The following set are the same for RedHat and Debian OS family
- include_tasks: define_timezone.yml
- include_tasks: chrony_service_install_config.yml
- include_tasks: create_private_ssh_key.yml
- include_tasks: update_sshd_config.yml
- include_tasks: configure_kernel_parameters.yml
- include_tasks: update_imapd_conf.yml
- include_tasks: install_common_packages.yml

# A block dedicated for ansible_os_family == "RedHat"
- block:
  - include_tasks: update_rh_packages.yml
  - include_tasks: copy_yum_repos.yml
  - include_tasks: install_rh_packages.yml
  - include_tasks: install_rear_rh_packages.sh

  when: ansible_os_family == "RedHat"

# A block dedicated for ansible_os_family == "Debian"
- block:
  - include_tasks: update_deb_packages.yml
  - include_tasks: apt_add_rear_repositories.yml
  - include_tasks: install_deb_packages.yml
  - include_tasks: install_rear_deb_packages.yml

  when: ansible_os_family == "Debian"

#############################################
# Common tasks for RedHat and Ubuntu
- include_tasks: create_users.yml
- include_tasks: update_and_restart_network.yml
- include_tasks: disable_biosdevnames.yml
- include_tasks: change_selinux_state.yml


# Add various helpful configuration files
- name: Install the hosts file
  copy: src=hosts dest=/etc/hosts mode=0644

