---
# File ansible/common/roles/rear-test/tasks/update_all_packages.yml

- name: update all packages
  yum: name=* update_cache=yes state=latest

  # cannot use 'package: name=* state=latest' as on debian it would install ALL packages found, and not just update
  # the installed ones
